# Generated by Django 2.0.3 on 2018-09-21 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dependent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dependent_name', models.CharField(max_length=100)),
                ('dependent_age', models.IntegerField()),
                ('dependent_gender', models.CharField(choices=[('M', 'MALE'), ('F', 'FEMALE'), ('T', 'TRANS')], default='', max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('member_name', models.CharField(max_length=100)),
                ('member_age', models.IntegerField()),
                ('member_address', models.CharField(max_length=250)),
                ('contact_number', models.CharField(max_length=12)),
                ('join_date', models.DateField(default='')),
                ('member_photo', models.FileField(upload_to='')),
                ('member_bio', models.CharField(max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='dependent',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.Member'),
        ),
    ]
