# Generated by Django 2.0.3 on 2018-09-23 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_auto_20180918_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='file_type',
            field=models.CharField(default='', max_length=100),
        ),
    ]
